import type {
  LocalizedText,
  SandhiAnalysisResult,
  SandhiAnalysisStep,
  SandhiAnalyzeErrorResponse,
  SandhiAnalyzeSuccessResponse,
  SanskritInputScript,
  SurfaceForms,
} from "../../shared/contracts/sandhi.ts";
import type { WordNode } from "../types/sandhi";
import { makeWordId, splitDevanagariAksharas } from "./sanskrit";

type AnalysisTreeNode = {
  surface: SurfaceForms;
  step: SandhiAnalysisStep | null;
  left: AnalysisTreeNode | null;
  right: AnalysisTreeNode | null;
};

const sameSurface = (left: SurfaceForms, right: SurfaceForms) =>
  left.iast === right.iast && left.devanagari === right.devanagari;

const buildGeneratedExplanation = (
  step: SandhiAnalysisStep,
  surface: SurfaceForms,
): LocalizedText => ({
  en: `${step.left.devanagari} + ${step.right.devanagari} can yield ${surface.devanagari} by ${step.label.en}.`,
  sa: `${step.left.devanagari} + ${step.right.devanagari} इत्येताभ्यां ${step.label.sa} नियमेन ${surface.devanagari} सिद्ध्यति।`,
  te: `${step.left.devanagari} + ${step.right.devanagari} కలిస్తే ${step.label.te} ప్రకారం ${surface.devanagari} రావచ్చు.`,
});

const rebuildTreeFromSteps = (
  surface: SurfaceForms,
  steps: SandhiAnalysisStep[],
  cursor: { index: number },
  depth: number,
): AnalysisTreeNode => {
  const current = steps[cursor.index];

  if (
    !current ||
    current.depth !== depth ||
    !sameSurface(current.surface, surface)
  ) {
    return {
      surface,
      step: null,
      left: null,
      right: null,
    };
  }

  cursor.index += 1;

  return {
    surface,
    step: current,
    left: rebuildTreeFromSteps(current.left, steps, cursor, depth + 1),
    right: rebuildTreeFromSteps(current.right, steps, cursor, depth + 1),
  };
};

const responseSurface = (result: SandhiAnalysisResult, response: SandhiAnalyzeSuccessResponse) =>
  result.steps[0]?.surface ?? {
    iast: response.normalized.iast,
    devanagari: response.normalized.devanagari,
    telugu: response.normalized.telugu,
  };

const treeToWordNode = (
  node: AnalysisTreeNode,
  resultId: string,
): WordNode => {
  const counts = new Map<string, number>();

  const build = (current: AnalysisTreeNode, path: string): WordNode => {
    const baseId = makeWordId(current.surface.devanagari);
    const nextCount = (counts.get(baseId) ?? 0) + 1;
    counts.set(baseId, nextCount);

    const nodeId =
      path === "root"
        ? resultId
        : nextCount === 1
          ? `${baseId}-${path}`
          : `${baseId}-${path}-${nextCount}`;

    if (!current.step || !current.left || !current.right) {
      return {
        id: nodeId,
        devanagari: current.surface.devanagari,
        iast: current.surface.iast,
        telugu: current.surface.telugu,
        status: "final",
        aksharas: splitDevanagariAksharas(current.surface.devanagari),
        cuts: [],
      };
    }

    const leftNode = build(current.left, `${path}l`);
    const rightNode = build(current.right, `${path}r`);

    return {
      id: nodeId,
      devanagari: current.surface.devanagari,
      iast: current.surface.iast,
      telugu: current.surface.telugu,
      status: "splittable",
      aksharas: [...leftNode.aksharas, ...rightNode.aksharas],
      cuts: [
        {
          id: `${nodeId}-split`,
          ruleId: current.step.ruleId,
          cutAfterAksharaIndex: Math.max(leftNode.aksharas.length - 1, 0),
          left: leftNode,
          right: rightNode,
          explanation: {
            ...buildGeneratedExplanation(current.step, current.surface),
            nimitta: current.step.nimitta,
            note: "Generated by Sandhi Explorer.",
          },
          sutra: { ...current.step.sutra },
        },
      ],
    };
  };

  return build(node, "root");
};

export const requestSandhiAnalysis = async (
  input: string,
  script: SanskritInputScript,
  maxResults?: number,
) => {
  const response = await fetch("/api/sandhi/analyze", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      input,
      script,
      maxResults,
    }),
  });

  if (!response.ok) {
    const payload = (await response.json().catch(() => null)) as
      | SandhiAnalyzeErrorResponse
      | null;
    throw new Error(payload?.message ?? "Sandhi analysis request failed.");
  }

  return (await response.json()) as SandhiAnalyzeSuccessResponse;
};

export const analysisResultToWordNode = (
  result: SandhiAnalysisResult,
  response: SandhiAnalyzeSuccessResponse,
) => {
  const cursor = { index: 0 };
  const root = rebuildTreeFromSteps(
    responseSurface(result, response),
    result.steps,
    cursor,
    0,
  );

  return treeToWordNode(root, result.id);
};
